defaults: &defaults
  :datamapper:
    :adapter:  sqlite3
    :database: db/development.sqlite3

:development:
  <<: *defaults

:test:
  <<: *defaults

:production:
  <<: *defaults
  :datamapper:
    :adapter:  sqlite3
    :database: db/production.sqlite3
